### PR TITLE
Check for undefined or null and objects

### LINKED ISSUE #1: Cannot freeze object with Buffer property
```
> freeze = require('deep-freeze-node')
[Function]
> freeze({foo: new Buffer(1)})
TypeError: Cannot prevent extension of an object with external array elements
    at Function.freeze (native)
```

### PR DESCRIPTION
**Pull request by lumberj**
Fixes #1

### CODE REVIEW

**Comment by lumberj** [comment]
Realized, this won't work for objects created with `new`

**Comment by lumberj** [comment]
```
>
> MyClass {}
...
> MyClass { }
...
> class MyClass { }
[Function: MyClass]
> typeof (new MyClass())
'object'
> (new MyClass()) instanceof Object
true
> (new MyClass()).constructor
[Function: MyClass]
> (new MyClass()).constructor === Object
false
> Object.prototype.toString.call(new MyClass())
'[object Object]'
>
```

The best way to check for regular Objects (including those created with `new`) is with Object.prototype.toString() as in the last example

**Comment by lumberj** [comment]
Assuming this project is abandoned

**Comment by AnatoliyGatt** [comment]
@lumberj Hi, sorry for taking so long. Do you mind reopening this?

**Pull request closed without merging**
